/* ── GWR integer-code → multilingual label resolution ──────────────────────
   Several GWR attributes (building category, class, status, construction
   period, heating, …) come back from the API as integer codes. This module
   loads data/gwr-codes.json once (BFS Merkmalskatalog, generated by the sister
   gwr-check tool) and resolves those codes to DE/FR/IT labels. Resolution
   degrades gracefully to the raw code if the file can't be loaded. */

// GWR attribute name → its code table in gwr-codes.json.
export const CODE_TABLE = {
  // Building
  gkat: "GKAT",
  gklas: "GKLAS",
  gstat: "GSTAT",
  gbaup: "GBAUP",
  gksce: "GKSCE",
  ltyp: "LTYP",
  gschutzr: "GSCHUTZR",
  gvolnorm: "GVOLNORM",
  gvolsce: "GVOLSCE",
  // Heating / hot water (1 = most powerful system, 2 = secondary)
  gwaerzh1: "GWAERZH1",
  genh1: "GENH1",
  gwaersceh1: "GWAERSCEH1",
  gwaerzh2: "GWAERZH2",
  genh2: "GENH2",
  gwaersceh2: "GWAERSCEH2",
  gwaerzw1: "GWAERZW1",
  genw1: "GENW1",
  gwaerscew1: "GWAERSCEW1",
  gwaerzw2: "GWAERZW2",
  genw2: "GENW2",
  gwaerscew2: "GWAERSCEW2",
  // Entrance / address
  strsp: "STRSP",
  stroffiziel: "STROFFIZIEL",
  doffadr: "DOFFADR",
  // Dwelling
  wstwk: "WSTWK",
  wmehrg: "WMEHRG",
  wstat: "WSTAT",
  wkche: "WKCHE",
};

let codes = null;
let loading = null;

/** Fetch the code tables once (idempotent; concurrent callers share one fetch). */
export function loadCodes() {
  if (codes) return Promise.resolve(codes);
  if (loading) return loading;
  loading = fetch(new URL("../data/gwr-codes.json", import.meta.url))
    .then((res) => (res.ok ? res.json() : {}))
    .catch(() => ({}))
    .then((json) => (codes = json));
  return loading;
}

/**
 * Resolve a coded attribute to its label in `lang`, falling back to the raw
 * code (then DE) when no translation exists. Returns "" for empty/null codes.
 */
export function resolveCode(attr, code, lang) {
  if (code == null || code === "") return "";
  const entry = codes?.[CODE_TABLE[attr]]?.[String(code)];
  if (!entry) return String(code);
  return entry[lang] || entry.de || String(code);
}
